baseURL: https://cookiehanhoan.github.io/
languageCode: en-us
title: CookieHanHoan Security Blog
theme: "risotto"

paginate: 5

DefaultContentLanguage: en
enableInlineShortcodes: true
ignoreErrors:
  - error-remote-getjson
sectionPagesMenu: main
params:
  noindex: false
  theme:
    palette: base16-dark
  about:
    title: risotto
    description: 'Blog về bảo mật - Cookie Han Hoan'
    logo: images/rice.svg
  socialLinks:
    - icon: fa-brands fa-facebook
      title: Facebook
      url: 'https://www.facebook.com/cookie.han.hoan/'
    - icon: fa-brands fa-github
      title: GitHub
      url: 'https://github.com/cookiehanhoan'
    - icon: fa-solid fa-envelope
      title: Email
      url: 'mailto:hazy@cookiehanhoan.org'
        #- icon: ai ai-orcid
        #  title: ORCID
        #  url: 'https://orcid.org/0000-0001-2345-6789'
menu:
  main:
    - identifier: about
      name: About
      url: /about/
      weight: 10
taxonomies:
  category: categories
  tag: tags
  series: series
markup:
  goldmark:
    renderer:
      unsafe: true
privacy:
  vimeo:
    disabled: false
    simple: true
  twitter:
    disabled: false
    enableDNT: true
    simple: true
  instagram:
    disabled: false
    simple: true
  youtube:
    disabled: false
    privacyEnhanced: true
services:
  instagram:
    disableInlineCSS: true
  twitter:
    disableInlineCSS: true

